// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nspgahimwxzawlpchofm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcGdhaGltd3h6YXdscGNob2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzkxNTksImV4cCI6MjA2OTY1NTE1OX0.QlModAJcsM67yxLoGCzq0rXBmOZMev3D7VfUTBohvN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});